a = int(input("Enter Number 1 :"))
b = int(input("Enter Number 2 :"))
print("Num a is :",a)
print("Num b is :",b)
print("Sum is :", int(a)+int(b))
print("Sum is :", a+b)

c = input("Enter your name :")
d = input("Enter your age :")
print("Your name is :",c)
print("Your age is :",d)