Fruits= []
f1 = input("Enter Fruit1 :")
f2 = input("Enter Fruit2 :")        
f3 = input("Enter Fruit3 :")
f4 = input("Enter Fruit4 :")
f5 = input("Enter Fruit5 :")
f6 = input("Enter Fruit6 :")
f7 = input("Enter Fruit7 :")
Fruits.append(f1)
Fruits.append(f2)
Fruits.append(f3)
Fruits.append(f4)
Fruits.append(f5)
Fruits.append(f6)
Fruits.append(f7)
print(Fruits)