s= set()
num = input("Enter number  :")
s.add(int(num))
num = input("Enter number  :")
s.add(int(num))
num = input("Enter number  :")
s.add(int(num))
num = input("Enter number  :")
s.add(int(num))
num = input("Enter number  :")
s.add(int(num))
num = input("Enter number  :")
s.add(int(num))
num = input("Enter number  :")
s.add(int(num))
num = input("Enter number  :")
s.add(int(num))

print(s)